---
version: '3'
services:
  diskbench:
    image: repo.home.local/tlhakhan/app/diskbench:latest
    environment:
      - JOB_RUNTIME=300
      - JOB_CORES=4
      - JOB_FILESIZE=1g
    volumes:
      - bench:/bench
      - fio_tmp:/fio_tmp
    entrypoint: bash /bench/start.sh

volumes:
  bench:
  fio_tmp:
