---
version: '3'
services:
  diskbench:
    image: repo.home.local/tlhakhan/app/diskbench:latest
    environment:
      - JOB_RUNTIME=300
      - JOB_CORES=1
      - JOB_FILESIZE=512m
    volumes:
      - bench:/bench
    entrypoint: bash /bench/start.sh

volumes:
  bench:
