---
version: '3'
services:
  diskbench:
    environment:
      - JOB_RUNTIME=300
      - JOB_CORES=1
      - JOB_FILESIZE=512m
    build:
      context: ./diskbench
    volumes:
      - ./bench:/bench
    entrypoint: bash /bench/start.sh